[pytest]
# 忽略特定的目录，避免在这些目录中查找测试用例
norecursedirs = ignored_dir tests/drafts drafts

# 设置默认的测试收集规则，例如只收集以 test_ 开头或结尾的模块、函数和类
python_files = test_*.py *_test.py

# 设置命令行选项，这里设置为安静模式（只显示关键信息）和报告所有测试结果
addopts = -ra

# 设置日志级别，帮助调试测试过程中的问题
log_level = INFO

# 设置缓存目录，加速测试执行
cache_dir =.pytest_cache

# 设置失败时停止执行，方便快速定位问题
xfail_strict = true

# start command    export PYTHONPATH=. pytest
